<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { proxiesApi, type RowData } from "@/api/admin";
import StatusTag from "@/components/StatusTag.vue";

defineOptions({ name: "Proxies" });
const loading=ref(false);const rows=ref<RowData[]>([]);const visible=ref(false);const output=ref<RowData|null>(null);const editing=ref(false);const empty=()=>({id:0,name:"",kind:"shared",provider:"static",enabled:true,note:"",proxies:"",api_config:"{}",ipwo_protocol:"socks5",ipwo_host:"",ipwo_port:7878,ipwo_username:"",ipwo_password:"",ipwo_country:"PH",ipwo_state:"",ipwo_city:"",ipwo_session_mode:"sticky",ipwo_sticky_minutes:120});const form=reactive<RowData>(empty());
function entriesText(entries:any[]=[]){return entries.map(item=>typeof item==="string"?item:item.url||item.proxy||"").filter(Boolean).join("\n");}
async function load(){loading.value=true;try{rows.value=(await proxiesApi.list()).data||[];}catch(error:any){ElMessage.error(error.message);}finally{loading.value=false;}}
async function open(row?:RowData){Object.assign(form,empty());editing.value=Boolean(row);if(row){loading.value=true;try{const data=(await proxiesApi.detail(row.id)).data||{};const c=data.config||{};Object.assign(form,data,{proxies:entriesText(c.proxies),api_config:data.provider==="api"?JSON.stringify(c,null,2):"{}",ipwo_protocol:c.protocol||"socks5",ipwo_host:c.host||"",ipwo_port:c.port||7878,ipwo_username:c.username||"",ipwo_password:c.password||"",ipwo_country:c.country||"",ipwo_state:c.state||"",ipwo_city:c.city||"",ipwo_session_mode:c.session_mode||"sticky",ipwo_sticky_minutes:c.sticky_minutes||120});}finally{loading.value=false;}}visible.value=true;}
function payload(){let config:RowData;if(form.provider==="static")config={proxies:String(form.proxies||"").split(/\r?\n/).map(v=>v.trim()).filter(Boolean)};else if(form.provider==="api")config=JSON.parse(form.api_config||"{}");else config={protocol:form.ipwo_protocol,host:form.ipwo_host,port:Number(form.ipwo_port),username:form.ipwo_username,password:form.ipwo_password,country:form.ipwo_country,state:form.ipwo_state,city:form.ipwo_city,session_mode:form.ipwo_session_mode,sticky_minutes:Number(form.ipwo_sticky_minutes),session_param:"sid",state_param:"st"};return{name:form.name,kind:form.kind,provider:form.provider,enabled:Boolean(form.enabled),note:form.note,config};}
async function save(){try{if(editing.value)await proxiesApi.update(form.id,payload());else await proxiesApi.create(payload());visible.value=false;ElMessage.success("代理组已保存");await load();}catch(error:any){ElMessage.error(error.message);}}
async function action(row:RowData,name:string){if(name==="delete")await ElMessageBox.confirm(`确认删除代理组 ${row.name}？`,"代理组操作",{type:"warning"});loading.value=true;try{const result=await proxiesApi.action(row.id,name,name==="test"?{attempt_index:0,timeout_ms:15000}:{});output.value=result.data;ElMessage.success(result.message||"操作已完成");await load();}catch(error:any){if(error!=="cancel")ElMessage.error(error.message);}finally{loading.value=false;}}
onMounted(load);
</script>

<template><div class="admin-page" v-loading="loading"><header class="page-heading"><div><h1>代理管理</h1><p>{{rows.length}} 个代理组</p></div><div class="page-actions"><el-button type="primary" @click="open()">新增代理组</el-button></div></header><section class="content-panel"><el-table :data="rows" stripe><el-table-column prop="id" label="ID" width="70"/><el-table-column prop="name" label="名称" min-width="160"/><el-table-column prop="kind" label="用途" width="110"><template #default="{row}">{{row.kind==='checkout'?'提链':row.kind==='direct_card'?'直卡':'共用'}}</template></el-table-column><el-table-column prop="provider" label="来源" width="100"/><el-table-column prop="enabled" label="状态" width="100"><template #default="{row}"><StatusTag :status="row.enabled?'enabled':'disabled'"/></template></el-table-column><el-table-column prop="note" label="备注" min-width="180"/><el-table-column label="操作" fixed="right" width="200"><template #default="{row}"><div class="action-row"><el-button link type="primary" @click="open(row)">编辑</el-button><el-button link @click="action(row,'test')">连通测试</el-button><el-button link type="danger" @click="action(row,'delete')">删除</el-button></div></template></el-table-column></el-table></section><section v-if="output" class="content-panel"><div class="panel-heading"><h2>测试结果</h2><el-button text @click="output=null">关闭</el-button></div><pre class="log-console">{{JSON.stringify(output,null,2)}}</pre></section>
<el-dialog v-model="visible" :title="editing?'编辑代理组':'新增代理组'" width="760px"><el-form label-position="top"><div class="form-grid"><el-form-item label="名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="用途"><el-select v-model="form.kind"><el-option label="提链" value="checkout"/><el-option label="直卡" value="direct_card"/><el-option label="共用" value="shared"/></el-select></el-form-item><el-form-item label="来源"><el-segmented v-model="form.provider" :options="[{label:'静态代理',value:'static'},{label:'IPWO',value:'ipwo'},{label:'API',value:'api'}]"/></el-form-item><el-form-item label="启用"><el-switch v-model="form.enabled"/></el-form-item><template v-if="form.provider==='static'"><el-form-item class="full-span" label="代理列表"><el-input v-model="form.proxies" type="textarea" :rows="6" placeholder="每行一个 https:// 或 socks5:// 代理"/></el-form-item></template><template v-else-if="form.provider==='api'"><el-form-item class="full-span" label="API 配置 JSON"><el-input v-model="form.api_config" type="textarea" :rows="8"/></el-form-item></template><template v-else><el-form-item label="协议"><el-select v-model="form.ipwo_protocol"><el-option label="SOCKS5" value="socks5"/><el-option label="HTTP/HTTPS" value="http"/></el-select></el-form-item><el-form-item label="主机"><el-input v-model="form.ipwo_host"/></el-form-item><el-form-item label="端口"><el-input-number v-model="form.ipwo_port" :min="1" :max="65535"/></el-form-item><el-form-item label="用户名"><el-input v-model="form.ipwo_username"/></el-form-item><el-form-item label="密码"><el-input v-model="form.ipwo_password" type="password" show-password/></el-form-item><el-form-item label="国家/地区"><el-input v-model="form.ipwo_country"/></el-form-item><el-form-item label="州/省"><el-input v-model="form.ipwo_state"/></el-form-item><el-form-item label="城市"><el-input v-model="form.ipwo_city"/></el-form-item><el-form-item label="会话模式"><el-select v-model="form.ipwo_session_mode"><el-option label="粘性 IP" value="sticky"/><el-option label="轮换 IP" value="rotate"/></el-select></el-form-item><el-form-item label="有效期（分钟）"><el-input-number v-model="form.ipwo_sticky_minutes" :min="1" :max="43200"/></el-form-item></template><el-form-item class="full-span" label="备注"><el-input v-model="form.note"/></el-form-item></div></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></div></template>
