<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { billingApi, type RowData } from "@/api/admin";
import StatusTag from "@/components/StatusTag.vue";

defineOptions({ name: "Billing" });
const loading=ref(false);const groups=ref<RowData[]>([]);const addresses=ref<RowData[]>([]);const groupVisible=ref(false);const addressVisible=ref(false);const editing=ref(false);const groupForm=reactive({name:"",note:""});const emptyAddress=()=>({id:0,billing_group_id:0,name:"",country:"PH",state:"",city:"",postal_code:"",line1:"",priority:100,status:"enabled",note:""});const addressForm=reactive<RowData>(emptyAddress());
const groupName=(id:number)=>groups.value.find(item=>Number(item.id)===Number(id))?.name||`#${id}`;
async function load(){loading.value=true;try{const [g,a]=await Promise.all([billingApi.groups(),billingApi.addresses()]);groups.value=g.data||[];addresses.value=a.data||[];}catch(error:any){ElMessage.error(error.message);}finally{loading.value=false;}}
async function createGroup(){try{await billingApi.createGroup(groupForm);groupVisible.value=false;Object.assign(groupForm,{name:"",note:""});ElMessage.success("账单组已新增");await load();}catch(error:any){ElMessage.error(error.message);}}
function openAddress(row?:RowData){Object.assign(addressForm,emptyAddress(),row||{});editing.value=Boolean(row);addressVisible.value=true;}
async function saveAddress(){try{const payload={...addressForm,billing_group_id:Number(addressForm.billing_group_id),priority:Number(addressForm.priority)};if(editing.value)await billingApi.updateAddress(addressForm.id,payload);else await billingApi.createAddress(payload);addressVisible.value=false;ElMessage.success("账单地址已保存");await load();}catch(error:any){ElMessage.error(error.message);}}
async function groupAction(row:RowData,action:string){if(action==="delete")await ElMessageBox.confirm(`确认删除账单组 ${row.name}？`,"账单组操作",{type:"warning"});try{await billingApi.groupAction(row.id,action);ElMessage.success("账单组状态已更新");await load();}catch(error:any){if(error!=="cancel")ElMessage.error(error.message);}}
async function addressAction(row:RowData,action:string){if(action==="delete")await ElMessageBox.confirm(`确认删除地址 ${row.name}？`,"账单地址操作",{type:"warning"});try{await billingApi.addressAction(row.id,action);ElMessage.success("账单地址状态已更新");await load();}catch(error:any){if(error!=="cancel")ElMessage.error(error.message);}}
onMounted(load);
</script>

<template><div class="admin-page" v-loading="loading">
  <header class="page-heading"><div><h1>账单资料</h1><p>{{groups.length}} 个账单组 · {{addresses.length}} 条地址</p></div><div class="page-actions"><el-button @click="groupVisible=true">新增账单组</el-button><el-button type="primary" @click="openAddress()">新增账单地址</el-button></div></header>
  <section class="content-panel"><div class="panel-heading"><h2>账单组</h2></div><el-table :data="groups" size="small"><el-table-column prop="id" label="ID" width="70"/><el-table-column prop="name" label="名称" min-width="180"/><el-table-column prop="note" label="备注" min-width="240"/><el-table-column label="操作" width="100"><template #default="{row}"><el-button link type="danger" @click="groupAction(row,'delete')">删除</el-button></template></el-table-column></el-table></section>
  <section class="content-panel"><div class="panel-heading"><h2>账单地址</h2></div><el-table :data="addresses" stripe><el-table-column prop="id" label="ID" width="70"/><el-table-column prop="name" label="姓名" min-width="120"/><el-table-column label="账单组" min-width="130"><template #default="{row}">{{groupName(row.billing_group_id)}}</template></el-table-column><el-table-column label="地区" min-width="170"><template #default="{row}">{{row.country}} {{row.state}} {{row.city}}</template></el-table-column><el-table-column prop="line1" label="地址" min-width="220" show-overflow-tooltip/><el-table-column prop="status" label="状态" width="100"><template #default="{row}"><StatusTag :status="row.status"/></template></el-table-column><el-table-column label="操作" fixed="right" width="220"><template #default="{row}"><div class="action-row"><el-button link type="primary" @click="openAddress(row)">编辑</el-button><el-button v-if="row.status==='disabled'" link type="success" @click="addressAction(row,'restore')">恢复</el-button><el-button v-else link @click="addressAction(row,'disable')">禁用</el-button><el-button link type="danger" @click="addressAction(row,'delete')">删除</el-button></div></template></el-table-column></el-table></section>
  <el-dialog v-model="groupVisible" title="新增账单组" width="480px"><el-form label-position="top"><el-form-item label="名称"><el-input v-model="groupForm.name"/></el-form-item><el-form-item label="备注"><el-input v-model="groupForm.note"/></el-form-item></el-form><template #footer><el-button @click="groupVisible=false">取消</el-button><el-button type="primary" @click="createGroup">新增</el-button></template></el-dialog>
  <el-dialog v-model="addressVisible" :title="editing?'编辑账单地址':'新增账单地址'" width="700px"><el-form label-position="top"><div class="form-grid"><el-form-item label="账单组"><el-select v-model="addressForm.billing_group_id"><el-option v-for="item in groups" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="状态"><el-select v-model="addressForm.status"><el-option label="启用" value="enabled"/><el-option label="禁用" value="disabled"/></el-select></el-form-item><el-form-item label="姓名"><el-input v-model="addressForm.name"/></el-form-item><el-form-item label="国家"><el-input v-model="addressForm.country"/></el-form-item><el-form-item label="州/省"><el-input v-model="addressForm.state"/></el-form-item><el-form-item label="城市"><el-input v-model="addressForm.city"/></el-form-item><el-form-item label="邮编"><el-input v-model="addressForm.postal_code"/></el-form-item><el-form-item label="优先级"><el-input-number v-model="addressForm.priority"/></el-form-item><el-form-item class="full-span" label="地址"><el-input v-model="addressForm.line1"/></el-form-item><el-form-item class="full-span" label="备注"><el-input v-model="addressForm.note"/></el-form-item></div></el-form><template #footer><el-button @click="addressVisible=false">取消</el-button><el-button type="primary" @click="saveAddress">保存</el-button></template></el-dialog>
</div></template>
