<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { cardsApi, type RowData } from "@/api/admin";
import StatusTag from "@/components/StatusTag.vue";
import ProviderPanel from "@/components/ProviderPanel.vue";
import { useResourcesStore } from "@/store/modules/resources";

defineOptions({ name: "Cards" });
const resources=useResourcesStore();const active=ref("cards");const createGroupVisible=ref(false);const createCardVisible=ref(false);const detailVisible=ref(false);const loading=ref(false);const groupForm=reactive({name:"",note:""});const cardForm=reactive<RowData>({card_group_id:0,status:"enabled",number:"",exp_month:"",exp_year:"",cvc:"",priority:100,max_success_count:1,provider:"",provider_card_id:"",auto_unfreeze_before_use:false,auto_freeze_after_success:false,auto_freeze_after_failure:false,note:""});const edit=reactive<RowData>({});const rechargeAmount=ref("");
const groupName=computed(()=>Object.fromEntries(resources.cardGroups.map(item=>[item.id,item.name])));
function policyText(row:RowData){const labels=[];if(row.auto_unfreeze_before_use)labels.push("用前解冻");if(row.auto_freeze_after_success)labels.push("成功后冻结");if(row.auto_freeze_after_failure)labels.push("失败后冻结");return labels.join(" · ")||"手动";}
async function refresh(){loading.value=true;try{await resources.load(true);}catch(error:any){ElMessage.error(error.message);}finally{loading.value=false;}}
async function createGroup(){try{await cardsApi.createGroup(groupForm);createGroupVisible.value=false;Object.assign(groupForm,{name:"",note:""});ElMessage.success("卡组已新增");await refresh();}catch(error:any){ElMessage.error(error.message);}}
async function createCard(){try{await cardsApi.create({...cardForm,card_group_id:Number(cardForm.card_group_id)});createCardVisible.value=false;ElMessage.success("卡已新增");await refresh();}catch(error:any){ElMessage.error(error.message);}}
async function openCard(row:RowData){try{Object.assign(edit,(await cardsApi.detail(row.id,true)).data||{});detailVisible.value=true;}catch(error:any){ElMessage.error(error.message);}}
async function saveCard(){try{await cardsApi.update(edit.id,{...edit,card_group_id:Number(edit.card_group_id),priority:Number(edit.priority),max_success_count:Number(edit.max_success_count)});ElMessage.success("卡信息已保存");await refresh();await openCard(edit);}catch(error:any){ElMessage.error(error.message);}}
async function action(row:RowData,name:string,payload:RowData={}){if(["delete","cancel"].includes(name))await ElMessageBox.confirm("确认执行此操作？","卡片操作",{type:"warning"});try{const data=(await cardsApi.action(row.id,name,payload)).data;ElMessage.success("操作已完成");if(data)Object.assign(edit,data);await refresh();}catch(error:any){if(error!=="cancel")ElMessage.error(error.message);}}
async function groupAction(row:RowData,name:string){if(name==="delete")await ElMessageBox.confirm(`确认删除卡组 ${row.name}？`,"卡组操作",{type:"warning"});try{await cardsApi.groupAction(row.id,name);ElMessage.success("卡组状态已更新");await refresh();}catch(error:any){if(error!=="cancel")ElMessage.error(error.message);}}
async function recharge(){if(!rechargeAmount.value){ElMessage.warning("请输入充值金额");return;}await action(edit,`${edit.provider}-recharge`,{amount:rechargeAmount.value});}
onMounted(refresh);
</script>

<template><div class="admin-page" v-loading="loading||resources.loading">
  <header class="page-heading"><div><h1>卡池管理</h1><p>{{ resources.cards.length }} 张卡 · {{ resources.cardGroups.length }} 个卡组</p></div><div class="page-actions"><el-button @click="createGroupVisible=true">新增卡组</el-button><el-button type="primary" @click="createCardVisible=true">新增卡</el-button></div></header>
  <section class="content-panel"><el-tabs v-model="active"><el-tab-pane label="本地卡池" name="cards">
    <div class="panel-heading"><h2>卡组</h2></div><el-table :data="resources.cardGroups" size="small"><el-table-column prop="id" label="ID" width="70"/><el-table-column prop="name" label="名称" min-width="160"/><el-table-column label="统计" min-width="230"><template #default="{row}"><span class="mono">enabled {{row.stats?.enabled||0}} · standby {{row.stats?.standby||0}} · disabled {{row.stats?.disabled||0}}</span></template></el-table-column><el-table-column label="操作" width="90"><template #default="{row}"><el-button link type="danger" @click="groupAction(row,'delete')">删除</el-button></template></el-table-column></el-table>
    <div class="panel-heading mt-6"><h2>卡列表</h2></div><el-table :data="resources.cards" stripe><el-table-column prop="id" label="ID" width="70"/><el-table-column prop="masked_number" label="卡号" min-width="150"><template #default="{row}"><span class="mono">{{row.masked_number}}</span></template></el-table-column><el-table-column label="卡组" min-width="130"><template #default="{row}">{{groupName[row.card_group_id]||`#${row.card_group_id}`}}</template></el-table-column><el-table-column prop="provider" label="来源" width="100"><template #default="{row}">{{row.provider?row.provider.toUpperCase():'本地'}}</template></el-table-column><el-table-column label="自动策略" min-width="220"><template #default="{row}">{{policyText(row)}}</template></el-table-column><el-table-column prop="status" label="状态" width="100"><template #default="{row}"><StatusTag :status="row.status"/></template></el-table-column><el-table-column label="成功次数" width="100"><template #default="{row}">{{row.success_count}}/{{row.max_success_count}}</template></el-table-column><el-table-column label="操作" width="280" fixed="right"><template #default="{row}"><div class="action-row"><el-button link type="primary" @click="openCard(row)">查看/编辑</el-button><el-button v-if="row.status==='disabled'" link type="success" @click="action(row,'restore')">恢复</el-button><el-button v-else link @click="action(row,'disable')">禁用</el-button><el-button link type="success" @click="action(row,'success')">记成功</el-button><el-button link type="danger" @click="action(row,'delete')">删除</el-button></div></template></el-table-column></el-table>
  </el-tab-pane><el-tab-pane label="VCC 卡台" name="vcc" lazy><ProviderPanel provider="vcc"/></el-tab-pane><el-tab-pane label="Kimoox 卡台" name="kimoox" lazy><ProviderPanel provider="kimoox"/></el-tab-pane></el-tabs></section>
  <el-dialog v-model="createGroupVisible" title="新增卡组" width="480px"><el-form label-position="top"><el-form-item label="名称"><el-input v-model="groupForm.name"/></el-form-item><el-form-item label="备注"><el-input v-model="groupForm.note"/></el-form-item></el-form><template #footer><el-button @click="createGroupVisible=false">取消</el-button><el-button type="primary" @click="createGroup">新增</el-button></template></el-dialog>
  <el-dialog v-model="createCardVisible" title="新增卡" width="680px"><el-form label-position="top"><div class="form-grid"><el-form-item label="卡组"><el-select v-model="cardForm.card_group_id"><el-option v-for="item in resources.cardGroups" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="状态"><el-select v-model="cardForm.status"><el-option label="启用" value="enabled"/><el-option label="备用" value="standby"/><el-option label="禁用" value="disabled"/></el-select></el-form-item><el-form-item class="full-span" label="卡号"><el-input v-model="cardForm.number"/></el-form-item><el-form-item label="有效月"><el-input v-model="cardForm.exp_month"/></el-form-item><el-form-item label="有效年"><el-input v-model="cardForm.exp_year"/></el-form-item><el-form-item label="CVC"><el-input v-model="cardForm.cvc"/></el-form-item><el-form-item label="优先级"><el-input-number v-model="cardForm.priority"/></el-form-item><el-form-item label="最大成功次数"><el-input-number v-model="cardForm.max_success_count" :min="1"/></el-form-item><el-form-item label="远程来源"><el-select v-model="cardForm.provider" clearable><el-option label="VCC" value="vcc"/><el-option label="Kimoox" value="kimoox"/></el-select></el-form-item><el-form-item label="远程卡 ID"><el-input v-model="cardForm.provider_card_id"/></el-form-item><el-form-item class="full-span" label="自动策略"><div class="action-row"><el-checkbox v-model="cardForm.auto_unfreeze_before_use">使用前解冻</el-checkbox><el-checkbox v-model="cardForm.auto_freeze_after_success">成功后冻结</el-checkbox><el-checkbox v-model="cardForm.auto_freeze_after_failure">失败后冻结</el-checkbox></div></el-form-item><el-form-item class="full-span" label="备注"><el-input v-model="cardForm.note"/></el-form-item></div></el-form><template #footer><el-button @click="createCardVisible=false">取消</el-button><el-button type="primary" @click="createCard">新增卡</el-button></template></el-dialog>
  <el-drawer v-model="detailVisible" title="卡片详情" size="min(650px,92vw)"><el-descriptions :column="2" border><el-descriptions-item label="完整卡号"><span class="mono">{{edit.number}}</span></el-descriptions-item><el-descriptions-item label="有效期">{{edit.exp_month}}/{{edit.exp_year}}</el-descriptions-item><el-descriptions-item label="CVC"><span class="mono">{{edit.cvc}}</span></el-descriptions-item><el-descriptions-item label="来源">{{edit.provider||'本地'}}</el-descriptions-item></el-descriptions><el-form label-position="top" class="mt-5"><div class="form-grid"><el-form-item label="卡组"><el-select v-model="edit.card_group_id"><el-option v-for="item in resources.cardGroups" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="状态"><el-select v-model="edit.status"><el-option label="启用" value="enabled"/><el-option label="备用" value="standby"/><el-option label="禁用" value="disabled"/></el-select></el-form-item><el-form-item class="full-span" label="卡号"><el-input v-model="edit.number"/></el-form-item><el-form-item label="有效月"><el-input v-model="edit.exp_month"/></el-form-item><el-form-item label="有效年"><el-input v-model="edit.exp_year"/></el-form-item><el-form-item label="CVC"><el-input v-model="edit.cvc"/></el-form-item><el-form-item label="优先级"><el-input-number v-model="edit.priority"/></el-form-item><el-form-item label="最大成功次数"><el-input-number v-model="edit.max_success_count" :min="1"/></el-form-item><el-form-item label="远程来源"><el-select v-model="edit.provider" clearable><el-option label="VCC" value="vcc"/><el-option label="Kimoox" value="kimoox"/></el-select></el-form-item><el-form-item label="远程卡 ID"><el-input v-model="edit.provider_card_id" placeholder="可留空用卡号操作"/></el-form-item><el-form-item class="full-span" label="自动策略"><div class="action-row"><el-checkbox v-model="edit.auto_unfreeze_before_use">使用前解冻</el-checkbox><el-checkbox v-model="edit.auto_freeze_after_success">成功后冻结</el-checkbox><el-checkbox v-model="edit.auto_freeze_after_failure">失败后冻结</el-checkbox></div></el-form-item><el-form-item class="full-span" label="备注"><el-input v-model="edit.note"/></el-form-item></div><el-button type="primary" @click="saveCard">保存卡信息</el-button></el-form><div v-if="edit.provider" class="mt-6"><div class="panel-heading"><h2>远程卡操作</h2></div><div class="action-row"><el-button @click="action(edit,`${edit.provider}-balance`)">查询余额</el-button><el-input v-model="rechargeAmount" placeholder="充值金额 USD" style="width:160px"/><el-button type="primary" @click="recharge">充值</el-button><el-button @click="action(edit,'freeze')">冻结</el-button><el-button @click="action(edit,'unfreeze')">解冻</el-button></div></div></el-drawer>
</div></template>
